# - ITMO.Sync

# Парсинг

# fetch_start: "09-01"
# fetch_end: "06-30"
# default_calendar_prefix: "ИТМО"
# include_url_field: true
# include_location: true


# Шаблоны
# Доступные переменные: {title}, {type}, {label}, {teacher}, {teacher_short}, {format}, {location}, {url}, {note}

# summary_template: "{label} {title} — {type}. {format}"
# description_template: "Преподаватель: {teacher}\n{format}\n{note}"

# booking_summary_template: "{label} Бронирование: {title}"
# booking_description_template: "{format}\n\n{note}"


# Исключение предметов из расписания
# Правила для полного удаления предметов:
# ignore:
#   - "История России"                      # Исключить весь предмет
#   - match: "Физическая культура"          # Только очные занятия
#     format: IN_PERSON
#   - match: "БЖД"                          # Только онлайн-лекции
#     type: LECTURE
#     format: REMOTE

# Переименование предметов
# Правила для переименования:
# renames:
#   - "Иностранный язык": "Английский"         # Переименовать предмет везде
#   - match: "Архитектура вычислительных систем"
#     type: LAB                              # Переименовать только лабораторные
#     format: IN_PERSON                      # и только если они очные
#     to: "АВС (Лабы)"


# Переименование типов
# Оставляй левую часть неизменной, правой — переименовывай

# type_names:
#   LECTURE: "Лекция"
#   PRACTICAL: "Практика"
#   LAB: "Лабораторная"
#   SPORT: "Спорт"
#   EXTERNAT: "Экстернат"
#   EXAM: "Экзамен"
#   CREDIT: "Зачет"
#   GRADED_CREDIT: "Диф. зачет"
#   CONSULTATION: "Консультация"
#   BOOKING: "Бронирование"


# Эмодзи
# Оставляй левую часть неизменной, правой — переименовывай

# labels:
#   LECTURE: "📚"
#   PRACTICAL: "🧪"
#   LAB: "🔬"
#   SPORT: "🏋️"
#   EXTERNAT: "🌍"
#   EXAM: "🔥"
#   CREDIT: "✅"
#   GRADED_CREDIT: "💯"
#   CONSULTATION: "💬"
#   BOOKING: "🗓️"

# default_label: "📝"


# Форматы проведения
# 1 - гибрид, 2 - очно, 3 - дистант

# format_labels:
#   1: "Смешанный формат"
#   2: "Очно"
#   3: "Дистанционно"
