rules:
  ignore:
    - "История России"                      # Исключить весь предмет
    - match: "Физическая культура"          # Исключить только очные занятия
      format: IN_PERSON
    - match: "БЖД"                          # Исключить только онлайн-лекции
      type: LECTURE
      format: REMOTE

  renames:
    - "Иностранный язык": "Английский"         # Переименовать предмет везде
    - match: "Архитектура вычислительных систем"
      type: LAB                              # Переименовать только лабораторные
      format: IN_PERSON                      # и только если они очные
      to: "АВС (Лабы)"
